In [4]:
from sqlalchemy import create_engine
import pandas as pd

In [5]:
engine = create_engine("postgresql://atharva@localhost:5432/sephora_db"
)

In [6]:
pd.read_sql("SELECT current_user;", engine)

  current_user
0      atharva

In [7]:
products_sql = pd.read_csv("../data/processed/products.csv")
ingredients = pd.read_csv("../data/processed/ingredients.csv")
product_ingredients = pd.read_csv("../data/processed/product_ingredients.csv")
reviews_sql = pd.read_csv("../data/processed/reviews.csv")

In [8]:
products_sql.to_sql("products", engine, if_exists="replace", index=False)
ingredients.to_sql("ingredients", engine, if_exists="replace", index=False)
product_ingredients.to_sql("product_ingredients", engine, if_exists="replace", index=False)
reviews_sql.to_sql("reviews", engine, if_exists="replace", index=False)

411

In [9]:
pd.read_sql("select count(*) from ingredients;", engine)

   count
0   8156